// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkhrhbcthdaeleeinmoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxraHJoYmN0aGRhZWxlZWlubW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjAzNjEsImV4cCI6MjA3MjU5NjM2MX0.cbO6_f6F0Q8JIqpB6KXO1aA7kFv6QNbSTIW7G63XfvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});